"""Regression proof for FIX-5-T13 -- the macOS shim's silent bridge-unreachable failure.

The defect: `reference/hidshim.c` is loaded into the Studio process through DYLD-level
shimming, had no diagnostic output at all (`grep -n "fprintf|stderr|syslog|log_"` returned
nothing), and falls through to the real hidapi when the bridge cannot be reached. The symptom
a user reports -- "buttons don't show" -- is therefore indistinguishable from "the deck is not
connected", and nothing survives the process for a later look.

What the fix adds: one bounded, append-only record per distinct failure reason, written to a
file (Studio launched from Finder has no visible stderr), naming the socket path, the errno and
a fixed reason class. It never carries the device serial or any capability, it never starts a
bridge or blocks, and the real-hidapi fallthrough is unchanged.

How this test gets at shipped code: the same host-model idiom the device lanes use
(`tests/test_devicezkgui_handoff.py`). `model.c` `#include`s the shipped `reference/hidshim.c`
verbatim, so `bridge_unreachable_diagnostic()` and the `hid_enumerate()` call site under test
are the shipped functions, not copies. The only substitutions are the two compile-time paths
(`D200_HIDSHIM_LOG_PATH`, `D200_HIDSHIM_SOCKET_PATH`), which point into the test's own
workspace so no test can read or write the operator's `/tmp/d200-hidshim.log`, the real bridge
socket, or the deck.

What this proves: the record's contents, its once-per-reason and bounded-size properties, that
it refuses a planted symlink and a directory, and that the shipped enumeration site emits it
when the bridge is unreachable. What it does NOT prove: that Studio itself logs anything, that
Studio was launched from Finder, or anything about a live deck -- none of that is reachable
without the real Studio copy and the deck, and neither is claimed here.
"""

from __future__ import annotations

import json
import re
import shutil
import stat
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
SHIM = ROOT / "reference" / "hidshim.c"

# The record's fixed key set. Nothing else may enter the published line: the shim has a
# device serial and a per-handle capability in the same process, and neither belongs here.
RECORD_KEYS = ["clock", "errno", "event", "hint", "monotonicMs", "pid", "reason", "socket"]
REASON_VOCABULARY = {"absent", "refused", "timeout", "protocol", "io"}
DEFAULT_LOG_PATH = "/tmp/d200-hidshim.log"
DEFAULT_SOCKET_PATH = "/tmp/d200-adb-bridge.sock"

MODEL_BODY = r"""
/* Host model: the shipped shim is spliced in verbatim above this main(). */
static void run_scenario(const char *scenario, const char *path)
{
    int index;
    if (!strcmp(scenario, "absent")) {
        bridge_unreachable_diagnostic(path, ENOENT);
    } else if (!strcmp(scenario, "once")) {
        for (index = 0; index < 5; index++) bridge_unreachable_diagnostic(path, ENOENT);
        for (index = 0; index < 3; index++) bridge_unreachable_diagnostic(path, ECONNREFUSED);
        bridge_unreachable_diagnostic(path, ENOENT);
    } else if (!strcmp(scenario, "vocabulary")) {
        for (index = 1; index <= 32; index++) bridge_unreachable_diagnostic(path, index);
    } else if (!strcmp(scenario, "two-reasons")) {
        bridge_unreachable_diagnostic(path, ENOENT);
        bridge_unreachable_diagnostic(path, ECONNREFUSED);
    } else if (!strcmp(scenario, "directory")) {
        bridge_unreachable_diagnostic(path, ENOENT);
    } else if (!strcmp(scenario, "enumerate")) {
        hid_device_info *found = hid_enumerate(0x2207, 0x0019);
        printf("enumerate=%s\n", found ? "listed" : "empty");
        hid_free_enumeration(found);
    } else {
        fprintf(stderr, "unknown scenario %s\n", scenario);
        exit(2);
    }
}

int main(int argc, char **argv)
{
    if (argc < 2) {
        fprintf(stderr, "usage: model <scenario> [log-path]\n");
        return 2;
    }
    run_scenario(argv[1], argc > 2 ? argv[2] : D200_HIDSHIM_LOG_PATH);
    return 0;
}
"""


def shim_constant(name: str) -> str:
    """The shipped value of one `#define`, so this test cannot drift from the source."""
    match = re.search(rf"^#define {name} (\S+)$", SHIM.read_text(encoding="utf-8"), re.MULTILINE)
    assert match, f"{name} is not defined in {SHIM}"
    return match.group(1)


def model_source() -> str:
    return (
        "/* Generated by tests/test_vendorbridge_shimlog.py. Do not edit. */\n"
        "\n".join(
            f"#include <{header}>"
            for header in (
                "dlfcn.h", "errno.h", "fcntl.h", "limits.h", "poll.h", "pthread.h",
                "stdint.h", "stdio.h", "stdlib.h", "string.h", "sys/socket.h",
                "sys/stat.h", "sys/un.h", "time.h", "unistd.h", "wchar.h",
            )
        )
        + "\n\n/* The shipped shim, verbatim. */\n"
        + f'#include "{SHIM}"\n'
        + MODEL_BODY
    )


def host_cc() -> str | None:
    return shutil.which("cc") or shutil.which("clang")


@pytest.fixture(scope="session")
def model(tmp_path_factory):
    """One compiled model binary per session, with both compile-time paths redirected."""
    workspace = tmp_path_factory.mktemp("shimlog")
    absent_socket = workspace / "provably-absent.sock"
    assert not absent_socket.exists()
    binary = compile_model(workspace, workspace / "default-shim.log", absent_socket)
    return {
        "binary": binary,
        "default_log": workspace / "default-shim.log",
        "absent_socket": absent_socket,
    }


@pytest.fixture(scope="session")
def long_socket_model(tmp_path_factory):
    """The same model with a socket path longer than the record's path bound."""
    workspace = tmp_path_factory.mktemp("shimlog-long")
    long_socket = workspace / ("p" * 200) / ("q" * 200) / "bridge.sock"
    assert len(str(long_socket)) > int(shim_constant("D200_HIDSHIM_SOCKET_CHARS"))
    binary = compile_model(workspace, workspace / "default-shim.log", long_socket)
    return {"binary": binary, "absent_socket": long_socket}


def compile_model(workspace: Path, log_path: Path, socket_path: Path) -> Path:
    cc = host_cc()
    if cc is None:
        pytest.skip("no host C compiler (cc/clang) available")
    source = workspace / "model.c"
    source.write_text(model_source(), encoding="utf-8")
    binary = workspace / "model"
    compiled = subprocess.run(
        [
            cc, "-Wall", "-Wextra", "-o", str(binary), str(source),
            f'-DD200_HIDSHIM_LOG_PATH="{log_path}"',
            f'-DD200_HIDSHIM_SOCKET_PATH="{socket_path}"',
        ],
        capture_output=True, text=True,
    )
    assert compiled.returncode == 0, compiled.stderr
    assert "warning" not in compiled.stderr.lower(), (
        "the spliced shim must stay warning-clean under -Wall -Wextra:\n" + compiled.stderr
    )
    return binary


def run_model(model, scenario: str, path: Path | None = None):
    command = [str(model["binary"]), scenario]
    if path is not None:
        command.append(str(path))
    return subprocess.run(command, capture_output=True, text=True, timeout=120)


def records(path: Path) -> list[dict]:
    lines = path.read_text(encoding="utf-8").splitlines()
    return [json.loads(line) for line in lines if line.strip()]


# --- the record itself -----------------------------------------------------------------

def test_a_default_log_path_and_a_compile_time_override_both_exist():
    """The shipped default is the documented one, and the model's redirect is a *default*
    override rather than a runtime lookup: nothing in the environment can steer it."""
    assert shim_constant("D200_HIDSHIM_LOG_PATH") == f'"{DEFAULT_LOG_PATH}"'
    assert shim_constant("D200_HIDSHIM_SOCKET_PATH") == f'"{DEFAULT_SOCKET_PATH}"'
    assert shim_constant("D200_HIDSHIM_LOG_REASONS") == "8"
    assert int(shim_constant("D200_HIDSHIM_LOG_LIMIT")) > 0
    # The record's own buffer must hold the fixed text plus the whole bounded path,
    # which is the C `#if` in the shim and the reason it cannot silently drop itself.
    assert (int(shim_constant("D200_HIDSHIM_LOG_CHARS"))
            - int(shim_constant("D200_HIDSHIM_SOCKET_CHARS")) >= 320)


def test_an_unreachable_bridge_is_reported_with_the_socket_the_errno_and_no_device_identity(
        model, tmp_path):
    destination = tmp_path / "shim.log"

    result = run_model(model, "absent", destination)

    assert result.returncode == 0, result.stderr
    entries = records(destination)
    assert len(entries) == 1
    entry = entries[0]
    assert entry["event"] == "hidshimBridgeUnreachable"
    assert entry["socket"] == str(model["absent_socket"]), (
        "the record must name the socket that was probed, not a generic message"
    )
    assert entry["errno"] == 2 and entry["reason"] == "absent"
    assert entry["clock"] == "host-monotonic" and isinstance(entry["monotonicMs"], int)
    assert entry["pid"] > 0
    assert "ghostdeck studio" in entry["hint"], (
        "the wording must name the same command the `play` refusal does (FIX-1-T19)"
    )
    assert sorted(entry) == RECORD_KEYS, "no serial, capability or report byte may enter the record"
    # The only strings are fixed vocabulary; a serial would have to be one of them.
    assert all(isinstance(entry[key], (int, str)) for key in entry)
    assert stat.S_IMODE(destination.stat().st_mode) == 0o600


def test_each_distinct_reason_is_recorded_once_and_repeats_are_dropped(model, tmp_path):
    """Studio enumerates in a loop: the failure repeats, the record must not."""
    destination = tmp_path / "shim.log"

    result = run_model(model, "once", destination)

    assert result.returncode == 0, result.stderr
    entries = records(destination)
    assert [entry["errno"] for entry in entries] == [2, 61], (
        "one line per distinct errno, in first-seen order"
    )
    assert [entry["reason"] for entry in entries] == ["absent", "refused"]


def test_the_reason_vocabulary_and_the_file_length_are_both_bounded(model, tmp_path):
    """32 distinct errnos in one process still produce at most the fixed number of lines."""
    destination = tmp_path / "shim.log"
    limit = int(shim_constant("D200_HIDSHIM_LOG_REASONS"))

    result = run_model(model, "vocabulary", destination)

    assert result.returncode == 0, result.stderr
    entries = records(destination)
    assert len(entries) == limit
    assert {entry["reason"] for entry in entries} <= REASON_VOCABULARY


def test_a_log_that_has_reached_its_size_bound_is_left_alone(model, tmp_path):
    destination = tmp_path / "shim.log"
    size = int(shim_constant("D200_HIDSHIM_LOG_LIMIT"))
    destination.write_bytes(b"x" * size)

    result = run_model(model, "two-reasons", destination)

    assert result.returncode == 0, result.stderr
    assert destination.read_bytes() == b"x" * size, "a bounded log must not grow past the bound"


def test_the_log_is_append_only_and_never_truncates_what_is_already_there(model, tmp_path):
    destination = tmp_path / "shim.log"
    destination.write_text('{"event":"pre-existing"}\n', encoding="utf-8")

    result = run_model(model, "two-reasons", destination)

    assert result.returncode == 0, result.stderr
    lines = destination.read_text(encoding="utf-8").splitlines()
    assert lines[0] == '{"event":"pre-existing"}'
    assert [json.loads(line)["errno"] for line in lines[1:]] == [2, 61]


def test_a_symlink_planted_at_the_log_path_is_not_written_through(model, tmp_path):
    victim = tmp_path / "victim"
    victim.write_text("ORIGINAL\n", encoding="utf-8")
    destination = tmp_path / "shim.log"
    destination.symlink_to(victim)

    result = run_model(model, "two-reasons", destination)

    assert result.returncode == 0, result.stderr
    assert victim.read_text(encoding="utf-8") == "ORIGINAL\n"
    assert destination.is_symlink(), "the foreign entry is left exactly as it was"


def test_a_directory_at_the_log_path_is_refused_not_traversed(model, tmp_path):
    destination = tmp_path / "shim.log"
    destination.mkdir()

    result = run_model(model, "directory", destination)

    assert result.returncode == 0, result.stderr
    assert destination.is_dir() and not any(destination.iterdir())


def test_a_socket_path_longer_than_the_record_bound_still_publishes_a_complete_record(
        long_socket_model, tmp_path):
    """The failure this pins: the first revision of this fix skipped the write when the
    formatted line did not fit its buffer, so a long socket path produced a zero-byte log and
    no diagnosis at all -- the same silence the fix exists to remove."""
    destination = tmp_path / "shim.log"
    bound = int(shim_constant("D200_HIDSHIM_SOCKET_CHARS"))
    long_socket = str(long_socket_model["absent_socket"])

    result = run_model(long_socket_model, "absent", destination)

    assert result.returncode == 0, result.stderr
    entries = records(destination)
    assert len(entries) == 1, "a record that does not fit must be bounded, never dropped"
    assert entries[0]["errno"] == 2 and entries[0]["reason"] == "absent"
    assert entries[0]["socket"] == long_socket[:bound]
    assert len(entries[0]["socket"]) == bound


# --- the shipped call site --------------------------------------------------------------

def test_the_shipped_enumeration_site_emits_the_record_and_still_falls_through(model):
    """The unit above proves the helper; this proves the fix is wired into `hid_enumerate`.

    A D200 enumeration with no bridge on the compiled-in socket path must (a) still return
    normally -- the real-hidapi fallthrough is `empty` here, not a crash or a hang -- and
    (b) leave the record behind. The 5s is the shim's own 25-attempt probe budget, unchanged.
    """
    binary, default_log, absent_socket = (
        model["binary"], model["default_log"], model["absent_socket"]
    )
    if default_log.exists():
        default_log.unlink()

    result = run_model(model, "enumerate")

    assert result.returncode == 0, result.stderr
    assert "enumerate=empty" in result.stdout
    assert not absent_socket.exists(), "the probe must not create the socket it looks for"
    entries = records(default_log)
    assert len(entries) == 1
    assert entries[0]["event"] == "hidshimBridgeUnreachable"
    assert entries[0]["errno"] == 2
    assert str(absent_socket) in entries[0]["socket"], (
        "the record must name the socket the shim actually probed"
    )
